services:
  sy_captcha.v2.form.type:
    class: Matt\SyCaptchaBundle\Form\Type\SyCaptchaRecaptchaV2Type
    public: true
    autowire: true
    arguments:
      - '%sy_captcha.recaptcha_v2.site_key%'
      - '%sy_captcha.enabled%'
      - '%sy_captcha.recaptcha_v2.api_host%'
    tags:
      - { name: form.type }
  sy_captcha.v3.form.type:
    class: Matt\SyCaptchaBundle\Form\Type\SyCaptchaRecaptchaV3Type
    public: true
    autowire: true
    arguments:
      - '%sy_captcha.recaptcha_v3.site_key%'
      - '%sy_captcha.enabled%'
      - '%sy_captcha.recaptcha_v3.api_host%'
    tags:
      - { name: form.type }
  sy_captcha.recaptcha.v2:
    class: ReCaptcha\ReCaptcha
    public: false
    arguments:
      - '%sy_captcha.recaptcha_v2.secret_key%'
  sy_captcha.recaptcha.v3:
    class: ReCaptcha\ReCaptcha
    public: false
    arguments:
      - '%sy_captcha.recaptcha_v3.secret_key%'
  sy_captcha.hcaptcha.form.type:
    class: Matt\SyCaptchaBundle\Form\Type\SyCaptchaHCaptchaType
    public: true
    autowire: true
    arguments:
      - '%sy_captcha.hcaptcha.site_key%'
      - '%sy_captcha.enabled%'
      - '%sy_captcha.hcaptcha.api_host%'
      - '%sy_captcha.hcaptcha.invisible%'
    tags:
      - { name: form.type }
  sy_captcha.v2.validator:
    class: Matt\SyCaptchaBundle\Validator\Constraints\SyCaptchaRecaptchaV2Validator
    public: true
    arguments:
      - '@sy_captcha.recaptcha.v2'
      - '%sy_captcha.enabled%'
      - '@sy_captcha.ip_resolver'
    tags:
      - { name: validator.constraint_validator }
  sy_captcha.v3.validator:
    class: Matt\SyCaptchaBundle\Validator\Constraints\SyCaptchaRecaptchaV3Validator
    public: true
    arguments:
      - '@sy_captcha.recaptcha.v3'
      - '%sy_captcha.enabled%'
      - '@sy_captcha.ip_resolver'
      - '%sy_captcha.recaptcha_v3.score_threshold%'
    tags:
      - { name: validator.constraint_validator }
  sy_captcha.hcaptcha.validator:
    class: Matt\SyCaptchaBundle\Validator\Constraints\SyCaptchaHCaptchaValidator
    public: true
    arguments:
      - '%sy_captcha.enabled%'
      - '@sy_captcha.ip_resolver'
      - '@sy_captcha.hcaptcha_resolver'
    tags:
      - { name: validator.constraint_validator }
  sy_captcha.ip_resolver:
    class: Matt\SyCaptchaBundle\Utilities\IpResolver
    public: false
    arguments:
      - '@request_stack'
  sy_captcha.hcaptcha_resolver:
    class: Matt\SyCaptchaBundle\HCaptcha\HCaptchaResponseResolver
    public: false
    arguments:
      - '%sy_captcha.hcaptcha.secret_key%'
#  Matt\SyCaptchaBundle\Form\Type\SyCaptchaRecaptchaV2Type: '@sy_captcha.v2.form.type'